<?php

/**
 * Backend Example: Processing Tokenized Card Payment
 *
 * This file shows how to process a payment using a card token
 * generated by tokenizecard.js on the frontend
 *
 * FLOW:
 * 1. Frontend: User fills card data
 * 2. Frontend: tokenizecard.js generates token
 * 3. Backend: Receives token (this file)
 * 4. Backend: Creates order with token
 */

use Illuminate\Http\Request;
use Kaninstein\LaravelPagarme\Facades\Pagarme;
use Kaninstein\LaravelPagarme\DTOs\OrderDTO;
use Kaninstein\LaravelPagarme\DTOs\OrderItemDTO;
use Kaninstein\LaravelPagarme\DTOs\CustomerDTO;
use Kaninstein\LaravelPagarme\DTOs\AddressDTO;
use Kaninstein\LaravelPagarme\DTOs\PhonesDTO;
use Kaninstein\LaravelPagarme\DTOs\PhoneDTO;
use Kaninstein\LaravelPagarme\DTOs\PaymentDTO;
use Kaninstein\LaravelPagarme\DTOs\CreditCardPaymentDTO;
use Kaninstein\LaravelPagarme\DTOs\CreditCardDTO;

/**
 * Example 1: Laravel Controller Method
 * Processing payment from tokenizecard.js
 */
class PaymentController extends Controller
{
    public function processPayment(Request $request)
    {
        // 1. Validate request
        $validated = $request->validate([
            'pagarmetoken' => 'required|string', // Token from tokenizecard.js
            'customer_name' => 'required|string|max:255',
            'customer_email' => 'required|email',
            'customer_document' => 'required|string',
            'customer_phone' => 'required|string',
            'amount' => 'required|numeric|min:0.01',
        ]);

        // 2. Convert amount to cents
        $amountInCents = (int)($validated['amount'] * 100);

        // 3. Create customer
        $customer = CustomerDTO::individual(
            name: $validated['customer_name'],
            email: $validated['customer_email'],
            cpf: $validated['customer_document'],
            phones: PhonesDTO::brazilian(
                mobilePhone: PhoneDTO::parseBrazilian($validated['customer_phone'])
            ),
            address: AddressDTO::brazilian(
                number: $request->input('address_number'),
                street: $request->input('address_street'),
                neighborhood: $request->input('address_neighborhood'),
                zipCode: $request->input('address_zipcode'),
                city: $request->input('address_city'),
                state: $request->input('address_state')
            )
        );

        // 4. Create order items
        $items = [
            OrderItemDTO::create(
                description: $request->input('product_description', 'Product'),
                quantity: $request->input('quantity', 1),
                amount: $amountInCents
            ),
        ];

        // 5. Create payment with TOKEN (não com dados do cartão!)
        $card = CreditCardDTO::fromToken($validated['pagarmetoken']);

        $creditCardPayment = CreditCardPaymentDTO::withCard(
            card: $card,
            installments: $request->input('installments', 1),
            statementDescriptor: 'MY STORE'
        );

        $payment = PaymentDTO::creditCard($creditCardPayment);

        // 6. Create order
        $order = OrderDTO::create(
            items: $items,
            customer: $customer,
            payment: $payment,
            code: 'ORDER-' . time()
        )->withIp($request->ip())
          ->withSessionId($request->session()->getId());

        // 7. Send to Pagar.me API
        try {
            $result = Pagarme::orders()->create($order->toArray());

            return response()->json([
                'success' => true,
                'order_id' => $result['id'],
                'status' => $result['status'],
                'charges' => $result['charges'],
            ]);

        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'error' => $e->getMessage(),
            ], 422);
        }
    }
}

/**
 * Example 2: Processing Multi-payment with Multiple Tokens
 * When using tokenizecard.js with multiple forms
 */
function processMultiPayment(Request $request)
{
    // Frontend sends: pagarmetoken-0, pagarmetoken-1, etc.
    $tokens = [];
    $index = 0;

    while ($request->has("pagarmetoken-{$index}")) {
        $tokens[] = $request->input("pagarmetoken-{$index}");
        $index++;
    }

    if (empty($tokens)) {
        return response()->json(['error' => 'No payment tokens found'], 422);
    }

    // Create customer
    $customer = CustomerDTO::individual(
        name: $request->input('customer_name'),
        email: $request->input('customer_email'),
        cpf: $request->input('customer_document'),
        phones: PhonesDTO::brazilian(
            mobilePhone: PhoneDTO::parseBrazilian($request->input('customer_phone'))
        )
    );

    // Create items
    $totalAmount = (int)($request->input('total_amount') * 100);
    $items = [
        OrderItemDTO::create('Product', 1, $totalAmount),
    ];

    // Create payments from tokens
    $payments = [];
    $amountPerPayment = (int)($totalAmount / count($tokens));

    foreach ($tokens as $token) {
        $card = CreditCardDTO::fromToken($token);
        $creditCardPayment = CreditCardPaymentDTO::withCard($card);

        $payments[] = PaymentDTO::creditCard(
            creditCard: $creditCardPayment,
            amount: $amountPerPayment
        );
    }

    // Create order with multiple payments
    $order = new OrderDTO(
        items: $items,
        customer: $customer,
        payments: $payments
    );

    // Send to API
    try {
        $result = Pagarme::orders()->create($order->toArray());
        return response()->json(['success' => true, 'order_id' => $result['id']]);
    } catch (\Exception $e) {
        return response()->json(['error' => $e->getMessage()], 422);
    }
}

/**
 * Example 3: Saving Card Token for Future Use
 * Create a card in customer's wallet using token
 */
function saveCardFromToken(Request $request)
{
    $validated = $request->validate([
        'customer_id' => 'required|string',
        'pagarmetoken' => 'required|string',
    ]);

    try {
        // Create card in customer's wallet using token
        $card = Pagarme::customers()->createCard(
            customerId: $validated['customer_id'],
            cardData: [
                'token' => $validated['pagarmetoken'],
                'label' => $request->input('card_label', 'My Card'),
                'metadata' => [
                    'saved_at' => now()->toIso8601String(),
                ],
            ]
        );

        return response()->json([
            'success' => true,
            'card_id' => $card['id'],
            'last_four_digits' => $card['last_four_digits'],
            'brand' => $card['brand'],
        ]);

    } catch (\Exception $e) {
        return response()->json(['error' => $e->getMessage()], 422);
    }
}

/**
 * Example 4: Route Definition
 */
Route::post('/process-payment', [PaymentController::class, 'processPayment']);
Route::post('/process-multi-payment', 'processMultiPayment');
Route::post('/save-card-token', 'saveCardFromToken');

/**
 * Example 5: Simple Procedural Example
 */
function simpleTokenProcessing()
{
    // Simulating POST data from tokenizecard.js
    $_POST = [
        'pagarmetoken' => 'tok_abc123xyz',
        'customer_name' => 'João Silva',
        'customer_email' => 'joao@example.com',
        'amount' => '100.00',
    ];

    $token = $_POST['pagarmetoken'];
    $amountInCents = (int)($_POST['amount'] * 100);

    // Create customer
    $customer = CustomerDTO::individual(
        name: $_POST['customer_name'],
        email: $_POST['customer_email'],
        cpf: '12345678900',
        phones: PhonesDTO::brazilian(
            mobilePhone: PhoneDTO::brazilian('11', '987654321')
        )
    );

    // Create order with token
    $card = CreditCardDTO::fromToken($token);
    $payment = PaymentDTO::creditCard(
        CreditCardPaymentDTO::withCard($card)
    );

    $order = OrderDTO::create(
        items: [OrderItemDTO::create('Product', 1, $amountInCents)],
        customer: $customer,
        payment: $payment
    );

    // Send to Pagar.me
    $result = Pagarme::orders()->create($order->toArray());

    echo "Order created: " . $result['id'] . "\n";
}

/**
 * Example 6: Error Handling
 */
function processWithErrorHandling(Request $request)
{
    try {
        // Validate token presence
        if (!$request->has('pagarmetoken')) {
            throw new \Exception('Card token is required. Make sure tokenizecard.js is properly configured.');
        }

        $token = $request->input('pagarmetoken');

        // Validate token format
        if (!str_starts_with($token, 'tok_')) {
            throw new \Exception('Invalid token format. Token should start with "tok_"');
        }

        // Create payment
        $card = CreditCardDTO::fromToken($token);
        $payment = PaymentDTO::creditCard(
            CreditCardPaymentDTO::withCard($card, installments: 1)
        );

        // ... create order and process

        return response()->json(['success' => true]);

    } catch (\Kaninstein\LaravelPagarme\Exceptions\ValidationException $e) {
        // Token validation failed
        return response()->json([
            'error' => 'Invalid card data',
            'details' => $e->getMessage(),
        ], 422);

    } catch (\Kaninstein\LaravelPagarme\Exceptions\AuthenticationException $e) {
        // Invalid PUBLIC_KEY
        return response()->json([
            'error' => 'Authentication error. Check your PUBLIC_KEY configuration.',
        ], 401);

    } catch (\Exception $e) {
        // Generic error
        \Log::error('Payment processing error', [
            'error' => $e->getMessage(),
            'request' => $request->all(),
        ]);

        return response()->json([
            'error' => 'Payment processing failed. Please try again.',
        ], 500);
    }
}
